version: 2

sources:
  - name: my_jaffle
    database: my_jaffle
    schema: main
    description:  This is the database built with the raw csv files
    tables:
      - name: raw_customers
        columns:
          - name: id
            tests:
              - unique
          - name: name
            tests:
              - not_null

      - name: raw_items
        columns:
          - name: id
            tests:
              - unique
          - name: order_id
            tests:
              - not_null
          - name: sku
            tests:
              - not_null

      - name: raw_orders
        columns:
          - name: id
            tests:
              - unique
          - name: customer
            tests:
              - not_null
          - name: ordered_at
            tests:
              - not_null
          - name: store_id
            tests:
              - not_null
          - name: subtotal
            tests:
              - not_null
          - name: tax_paid
              - not_null
          - name: order_total
            tests:
              - not_null

      - name: raw_products
        columns:
          - name: sku
            tests:
              - unique
          - name: name
            tests:
              - not_null
          - name: type
            tests:
              - not_null
          - name: price
            tests:
              - not_null
          - name: description
            tests:
              - not_null

      - name: raw_stores
        columns:
          - name: id
            tests:
              - unique
          - name: name
            tests:
              - not_null
          - name: opened_at
            tests:
              - not_null
          - name: tax_rate
            tests:
              - not_null

      - name: raw_supplies
        columns:
          - name: id
            tests:
              - not_null
          - name: name
            tests:
              - not_null
          - name: cost
            tests:
              - not_null
          - name: perishable
            tests:
              - not_null
          - name: sku
            tests:
              - not_null
    loader: duckdb
